#!/bin/bash

loggedInUser=$(stat -f "%Su" /dev/console)
loggedInUserID=$(id -u "${loggedInUser}")
launchctl bootstrap gui/"${loggedInUserID}" /Library/LaunchAgents/au.edu.vic.woodleigh.rollmarkingreminder.plist