[[remotes]]
git_url = "https://github.com/woodleighschool/.github"
ref = "main"
configs = ["lefthook.common.toml"]

[pre-commit.commands.zizmor]
glob = [".github/workflows/*.{yaml,yml}", ".github/actions/**/action.{yaml,yml}"]
