#!/bin/sh

echo "Running pre-install script in $2"

# Silent installation: skip the interactive coreaudiod-restart confirmation dialog
# used by Audinate's original installer.

# Unload manager
launchctl unload -w /Library/LaunchDaemons/com.audinate.dante.DanteVirtualSoundcard.plist > /dev/null 2>&1

# Unload driver if exists
if [ $(kextstat | grep -c com.audinate.dante.driver.NetworkAudioDriver) -ne 0 ]; then
	kextunload -b com.audinate.dante.driver.NetworkAudioDriver > /dev/null 2>&1
fi

if [ $(kextstat | grep -c com.audinate.dante.driver.DanteVirtualSoundcard) -ne 0 ]; then
	kextunload -b com.audinate.dante.driver.DanteVirtualSoundcard > /dev/null 2>&1
fi

# Remove DVS Audio PlugIn
rm -rf /Library/Audio/Plug-Ins/HAL/DvsAudioPlugIn.driver

# Remove DVS apps
rm -rf /Library/Application\ Support/Audinate/DanteVirtualSoundcard
rm -rf /Applications/Dante\ Virtual\ Soundcard*

# Force quit DVS if it's already running
killall "Dante Virtual Soundcard" > /dev/null 2>&1

exit 0
