#!/bin/bash

# Get the currently logged in user
CURRENT_USER=$(logname)

# Define the settings file path
SETTINGS_FILE="/Users/${CURRENT_USER}/Library/Application Support/Code/User/settings.json"

# Check if the settings file already exists
if [ ! -f "${SETTINGS_FILE}" ]; then
	# Create the directory for settings file if it doesn't exist
	mkdir -p "$(dirname "${SETTINGS_FILE}")"

	# Write the settings.json content
	cat >"${SETTINGS_FILE}" <<EOF
{
    "workbench.iconTheme": "eq-material-theme-icons-palenight",
    "security.workspace.trust.enabled": false,
    "workbench.colorTheme": "Community Material Theme Palenight High Contrast",
    "explorer.confirmDelete": false,
    "editor.accessibilitySupport": "off",
    "editor.insertSpaces": false,
    "editor.detectIndentation": false,
    "explorer.confirmDragAndDrop": false,
    "[python]": {
        "editor.formatOnType": true,
        "editor.defaultFormatter": "ms-python.autopep8"
    },
    "workbench.startupEditor": "none",
    "terminal.integrated.enableMultiLinePasteWarning": false,
	"http.proxyStrictSSL": false,
	"editor.fontLigatures": false,
	"python.defaultInterpreterPath": "/usr/local/bin/python3"
}
EOF

	# Fix permissions recursively on the Code folder
	chown -R "${CURRENT_USER}:staff" "/Users/${CURRENT_USER}/Library/Application Support/Code"
fi

# List of extensions to install
EXTENSIONS=(
	"Equinusocio.vsc-community-material-theme"
	"equinusocio.vsc-material-theme-icons"
	"ms-python.autopep8"
	"ms-python.python"
	"ms-python.vscode-pylance"
)

# Install each extension
for ext in "${EXTENSIONS[@]}"; do
	su ${CURRENT_USER} -c "/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --install-extension ${ext} --force"
done
