#!/bin/bash

# remove nomad
/usr/local/bin/authchanger -reset || :
killall NoMAD || :

rm -rf \
	/Applications/NoMAD.app \
	/Library/Security/SecurityAgentPlugins/NoMADLoginAD.bundle \
	/Library/LaunchAgents/com.trusourcelabs.NoMAD.plist \
	/Library/Managed\ Preferences/com.trusourcelabs.NoMAD.plist \
	/Library/Managed\ Preferences/*/com.trusourcelabs.NoMAD.plist \
	/usr/local/bin/authchanger \
	/Users/*/Library/LaunchAgents/com.trusourcelabs.NoMAD.plist || :

# Remove any empty directories.
find \
	'/Library/Managed Preferences' \
	-depth -maxdepth 1 -type d -empty -delete 2>/dev/null || :

# remove old xcreds
killall XCreds
if [ -d "/Applications/XCreds.app" ]; then
	rm -rf "/Applications/XCreds.app"
fi
