#!/bin/bash

# uninstall previous installation
UNINSTALLER="/Applications/FamilyZone/MobileZoneAgent/uninstall.app/Contents/MacOS/osx-x86_64"
if [[ -f "${UNINSTALLER}" ]]; then
	"${UNINSTALLER}" --mode unattended
fi

# install
/usr/sbin/installer -pkg /tmp/connecttemp/Connect.pkg -target /
/usr/sbin/installer -pkg /tmp/connecttemp/auth_agent.woodleigh_vic_familyzone.pkg -target /

# cleanup after ourselves
rm -rf /tmp/connecttemp