Identifier: com.github.woodleighschool.intune.DellCommandEndpointConfigure
ParentRecipe: com.github.woodleighschool.pkg.DellCommandEndpointConfigure
MinimumVersion: "2.3"

Input:
  DESCRIPTION: >-
    Dell Command | Endpoint Configure for Microsoft Intune applies Dell BIOS
    configuration profiles delivered by Intune and enables remote BIOS settings
    management for supported Dell client devices.
  DETECTION_FILE_OR_FOLDER: Dell.EndpointConfigure.WinServiceAgent.exe
  DETECTION_PATH: C:\Program Files\Dell\EndpointConfigure
  INSTALL_COMMAND: '"__SETUP_FILE__" /s'
  MINIMUM_SUPPORTED_WINDOWS_RELEASE: Windows11_23H2
  NAME: Dell Command | Endpoint Configure for Microsoft Intune
  PUBLISHER: Dell
  UNINSTALL_COMMAND: '"__SETUP_FILE__" /passthrough /x /s /v"/qn /norestart"'
  UPDATE_MODE: in_place

Process:
  - Processor: com.github.woodleighschool.wintune-autopkg.processors/WintuneWin32AppUploader
    Arguments:
      architecture:
        - amd64
      assignment_info:
        - all_assignment: AllDevices
          assignment_filter_display_name: Dell
          assignment_filter_type: include
          intent: required
      categories:
        - Utilities
      description: "%DESCRIPTION%"
      detection_file_or_folder: "%DETECTION_FILE_OR_FOLDER%"
      detection_path: "%DETECTION_PATH%"
      detection_type: file_version_at_least
      display_name: "%NAME%"
      install_command: "%INSTALL_COMMAND%"
      intunewin_path: "%intunewin_path%"
      minimum_supported_windows_release: "%MINIMUM_SUPPORTED_WINDOWS_RELEASE%"
      publisher: "%PUBLISHER%"
      setup_file: "%setup_file%"
      uninstall_command: "%UNINSTALL_COMMAND%"
      update_mode: "%UPDATE_MODE%"
      version: "%version%"